# Generated by Django 5.0.4 on 2025-11-04 12:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaDiaria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('atividades', models.JSONField(default=list, help_text='Lista de atividades diárias do aluno.')),
                ('observacoes_professor', models.TextField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendas_diarias', to='academico.aluno')),
            ],
            options={
                'verbose_name': 'Agenda Diária',
                'verbose_name_plural': 'Agendas Diárias',
                'ordering': ['-data'],
                'unique_together': {('aluno', 'data')},
            },
        ),
    ]
