# Generated by Django 5.0.4 on 2025-11-20 18:39

import apps.comunicacao.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0002_initial'),
        ('comunicacao', '0002_agendadiaria_escola'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comunicado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('conteudo', models.TextField()),
                ('data_publicacao', models.DateTimeField(auto_now_add=True)),
                ('data_validade', models.DateField(blank=True, help_text='Data até quando o comunicado é válido', null=True)),
                ('prioridade', models.CharField(choices=[('BAIXA', 'Baixa'), ('NORMAL', 'Normal'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='NORMAL', max_length=10)),
                ('total_curtidas', models.IntegerField(default=0)),
                ('total_comentarios', models.IntegerField(default=0)),
                ('autor', models.ForeignKey(limit_choices_to={'tipo_usuario__in': ['ADMIN_ESCOLA', 'PROFESSOR']}, on_delete=django.db.models.deletion.CASCADE, related_name='comunicados_criados', to=settings.AUTH_USER_MODEL)),
                ('escola', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comunicados', to='core.escola')),
                ('turma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comunicados', to='academico.turma')),
            ],
            options={
                'verbose_name': 'Comunicado',
                'verbose_name_plural': 'Comunicados',
                'ordering': ['-prioridade', '-data_publicacao'],
            },
        ),
        migrations.CreateModel(
            name='Momento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('FOTO', 'Foto'), ('VIDEO', 'Vídeo')], default='FOTO', max_length=10)),
                ('arquivo', models.FileField(help_text='Formatos aceitos: JPG, PNG, GIF, MP4, MOV, AVI. Tamanho máximo: 10MB', upload_to=apps.comunicacao.models.upload_momento_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'mp4', 'mov', 'avi'])])),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_momento', models.DateField(help_text='Data em que o momento ocorreu')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('total_curtidas', models.IntegerField(default=0)),
                ('total_comentarios', models.IntegerField(default=0)),
                ('alunos', models.ManyToManyField(blank=True, related_name='momentos', to='academico.aluno')),
                ('autor', models.ForeignKey(limit_choices_to={'tipo_usuario': 'PROFESSOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='momentos_criados', to=settings.AUTH_USER_MODEL)),
                ('escola', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='momentos', to='core.escola')),
                ('turma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='momentos', to='academico.turma')),
            ],
            options={
                'verbose_name': 'Momento',
                'verbose_name_plural': 'Momentos',
                'ordering': ['-data_momento', '-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='Curtida',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('comunicado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='curtidas', to='comunicacao.comunicado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curtidas', to=settings.AUTH_USER_MODEL)),
                ('momento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='curtidas', to='comunicacao.momento')),
            ],
            options={
                'verbose_name': 'Curtida',
                'verbose_name_plural': 'Curtidas',
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('texto', models.TextField(max_length=1000)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('comentario_pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='comunicacao.comentario')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to=settings.AUTH_USER_MODEL)),
                ('comunicado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='comunicacao.comunicado')),
                ('momento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='comunicacao.momento')),
            ],
            options={
                'verbose_name': 'Comentário',
                'verbose_name_plural': 'Comentários',
                'ordering': ['data_criacao'],
            },
        ),
        migrations.AddIndex(
            model_name='comunicado',
            index=models.Index(fields=['escola', '-data_publicacao'], name='comunicacao_escola__626204_idx'),
        ),
        migrations.AddIndex(
            model_name='comunicado',
            index=models.Index(fields=['turma', '-data_publicacao'], name='comunicacao_turma_i_f65819_idx'),
        ),
        migrations.AddIndex(
            model_name='momento',
            index=models.Index(fields=['escola', '-data_criacao'], name='comunicacao_escola__0f8341_idx'),
        ),
        migrations.AddIndex(
            model_name='momento',
            index=models.Index(fields=['turma', '-data_criacao'], name='comunicacao_turma_i_4bcd06_idx'),
        ),
        migrations.AddIndex(
            model_name='curtida',
            index=models.Index(fields=['momento', '-data_criacao'], name='comunicacao_momento_b6b01a_idx'),
        ),
        migrations.AddIndex(
            model_name='curtida',
            index=models.Index(fields=['comunicado', '-data_criacao'], name='comunicacao_comunic_2e6be4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='curtida',
            unique_together={('usuario', 'comunicado'), ('usuario', 'momento')},
        ),
        migrations.AddIndex(
            model_name='comentario',
            index=models.Index(fields=['momento', 'data_criacao'], name='comunicacao_momento_7e571f_idx'),
        ),
        migrations.AddIndex(
            model_name='comentario',
            index=models.Index(fields=['comunicado', 'data_criacao'], name='comunicacao_comunic_b7c631_idx'),
        ),
    ]
