# Generated by Django 5.0.4 on 2025-11-03 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0001_initial'),
        ('core', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professorturma',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_turmas', to='usuarios.perfilprofessor'),
        ),
        migrations.AddField(
            model_name='responsavelaluno',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_responsaveis', to='academico.aluno'),
        ),
        migrations.AddField(
            model_name='responsavelaluno',
            name='responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_alunos', to='usuarios.perfilresponsavel'),
        ),
        migrations.AddField(
            model_name='turma',
            name='escola',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turmas', to='core.escola'),
        ),
        migrations.AddField(
            model_name='turma',
            name='professor_principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turmas_principal', to='usuarios.perfilprofessor'),
        ),
        migrations.AddField(
            model_name='professorturma',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_professores', to='academico.turma'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='turma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alunos', to='academico.turma'),
        ),
        migrations.AlterUniqueTogether(
            name='materia',
            unique_together={('escola', 'nome')},
        ),
        migrations.AlterUniqueTogether(
            name='responsavelaluno',
            unique_together={('responsavel', 'aluno')},
        ),
        migrations.AlterUniqueTogether(
            name='turma',
            unique_together={('escola', 'nome', 'ano_letivo')},
        ),
        migrations.AlterUniqueTogether(
            name='professorturma',
            unique_together={('professor', 'turma', 'materia')},
        ),
    ]
